### ISSUE TITLE
"Multiple instances of Three.js being imported." warning, when working with npm packages of three.js and AR.js in one project

### ISSUE THREAD

**Issue by FireDragonGameStudio** [AR-js-org/AR.js#504]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug, at least as far as I can tell.

**What is the current behavior?**
When importing three.js and AR.js for Marker Tracking (via npm packages, a warning that "Multiple instances of Three.js being imported." when starting the project. I use Vite as a bundler, if that information helps.

MyScript.js
```javascript
import * as THREE from "three";
import * as THREEx from "@ar-js-org/ar.js/three.js/build/ar-threex";
```

I checked the three.js samples, they seem to import the three.js min library. May this be related?

I'll attach my package.json content too.
package.json
```
{
  "name": "three-js-first-try",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^3.2.3"
  },
  "dependencies": {
    "@ar-js-org/ar.js": "^3.4.3",
    "three": "^0.146.0"
  }
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I just created a new project and added the npm packages via `npm i three` and `npm i @ar-js-org/ar.js`. When using Vite as bundler, starting the project with `npx vite` and the web dev tools console will show the warning.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Firefox, Chrome on their latest versions.

**What is the expected behavior?**
No warning.

**If this is a feature request, what is motivation or use case for changing the behavior?**
not a feature request

## ❗ ❗  Post Edit by @kalwalt 

This warning may show if you are using divergent three.js versions, between the `three` version used by AR.js and that one used in your project, they should match!!
and import the classes from the module version `import { ArToolkitProfile } from "@ar-js-org/ar.js/three.js/build/ar-threex.mjs";` 
This is working at least for ar.mjs and ar-threex.mjs dist files and related classes.

**Comment by nickw1** [comment]
Does it work if you remove three from the dependencies?

I have a feeling the issue might be that AR.js already has a three.js dependency, so you are installing two separate copies of three.js

@kalwalt might know more as he developed the packaging system for AR.js.

**Comment by FireDragonGameStudio** [comment]
This was my first thought too, but when I remove three.js I can't no longer create scenes, renderer, etc... e.g.: `scene = new THREEx.Scene();` doesn't work.

**Comment by nickw1** [comment]
If you keep the three import, but remove it from the dependencies, does it work?

**Comment by FireDragonGameStudio** [comment]
Nope, unfortunately not :(

**Comment by nickw1** [comment]
Is this just with markers, does it work with location-based?

**Comment by FireDragonGameStudio** [comment]
The warning appears with location only too.

**Comment by kalwalt** [comment]
I had this issue in the past, but i don' t remember now how i solved, but i will look into It when i can.

**Comment by FireDragonGameStudio** [comment]
Thank you, will be greatly appreciated!

**Comment by nickw1** [comment]
Will try and have a look at location, but no guarantees I'll be able to solve it. I guess it's something to do with the packaging process.

**Comment by kalwalt** [comment]
> I have a feeling the issue might be that AR.js already has a three.js dependency, and the built AR.js bundle already contains a copy of three.js so you are importing two separate copies of three.js, at different versions.

Three is included as an external package in webpack https://github.com/AR-js-org/AR.js/blob/be7c9083df5a651c2ab978ddd7c1a33409c4d40b/webpack.config.js#L9-L22 it should prevent to create another instance.

Maybe add three to `devDependencies` in `package.json`? I have to admit i never used vite bundler so "i'm walking in the dark".
@FireDragonGameStudio Can you share more infos on your vite setup or do you have a github repository to have a look or test?

**Comment by kalwalt** [comment]
Another thing: Can you try instead to import the whole THREE namespace with: 
`import * as THREE from "three";`
only the classes that you need ? example:
`import { Mesh } from "three";`

**Comment by FireDragonGameStudio** [comment]
Thx for the swift response. I'm currently not at home, but I'll give it a shot as soon as I'm back. The repo for this is [https://github.com/FireDragonGameStudio/ARIndoorNavigation-Threejs](https://github.com/FireDragonGameStudio/ARIndoorNavigation-Threejs) but the current state is not pushed yet. Will do that as soon as I'm home too and give you an update here :)

**Comment by FireDragonGameStudio** [comment]
Unfortunately none of the suggested solutions helped. Neither moving `three` to `devDependencies`, nor only importing the needed classes. Tried to remove `three` completely, so maybe the dependency is resolved, deleted `node_modules` + `package-lock.json` too, but no change after npm install. Is it generally possible to use the AR.js three version? Smth. like `var scene = new THREEX.Scene();`?

I already pushed the current state of the project without installed three npm package, so feel free to check it out and play around.

Will try to bundle with webpack tomorrow. I have a feeling that Vite is messing with me... Oo

**Comment by kalwalt** [comment]
> Unfortunately none of the suggested solutions helped. Neither moving `three` to `devDependencies`, nor only importing the needed classes. Tried to remove `three` completely, so maybe the dependency is resolved, deleted `node_modules` + `package-lock.json` too, but no change after npm install. Is it generally possible to use the AR.js three version? Smth. like `var scene = new THREEX.Scene();`?
> 
> I already pushed the current state of the project without installed three npm package, so feel free to check it out and play around.
> 
> Will try to bundle with webpack tomorrow. I have a feeling that Vite is messing with me... Oo

I think it depends by the set up. I see that you specify in package.json https://github.com/FireDragonGameStudio/ARIndoorNavigation-Threejs/blob/a21badd7bbd2ef33512acf39ce849ec142a485ba/package.json#L5 
`"type": "module"` 
what happens if you disable  it and add three in the dependencies?

**Comment by FireDragonGameStudio** [comment]
The warning unfortunately still appears :/

**Comment by nickw1** [comment]
I thought I recognised this warning, but had not given it priority as it didn't stop anything working.

To investigate this, I've prepared an absolute basic location-based three.js example here:

https://github.com/nickw1/arjs-three-basic/

This uses `npm` to install AR.js and webpack to build.

My observations seem similar to @FireDragonGameStudio:

- if I import `THREE `from `three`, I get the multiple instances warning.
- if I don't import THREE, then hardly surprisingly, THREE is undefined.

@kalwalt does this help?

**Comment by kalwalt** [comment]
> I thought I recognised this warning, but had not given it priority as it didn't stop anything working.
> 
> To investigate this, I've prepared an absolute basic location-based three.js example here:
> 
> https://github.com/nickw1/arjs-three-basic/
> 
> This uses `npm` to install AR.js and webpack to build.
> 
> My observations seem similar to @FireDragonGameStudio:
> 
> * if I import `THREE `from `three`, I get the multiple instances warning.
> * if I don't import THREE, then hardly surprisingly, THREE is undefined.
> 
> @kalwalt does this help?

I can confirm this but i haven't a solution at the moment. Thank you @nickw1

**Comment by juanRabaa** [comment]
I think this is related to the way the build is bundling the files. I made a test modifying the UMD config of the `threex-location-only` to be built as a ESM instead. It does eliminate the multiple instances, but it removes the possibility of adding the file to a project any other way than by importing it as a module.

Meanwhile, there is a workaround in webpack that worked for me. Setting an `alias` in your config for `three` to be converted into `node_modules/three`

This is an answer from this post https://discourse.threejs.org/t/threejs-custom-lib-usage-generate-warning-multiple-instances-of-three-js-being-imported/35292/3

```js
module.exports = {
    // ...
    resolve: {
         // ...
        alias: {
            three: path.resolve('./node_modules/three')
        },
        // ...
    },
    // ...
};
```

**Comment by Platform-Group** [comment]
Thanks Juan, shame that I've already given up on Vue and gone back to barebones html, css and js now

**Comment by nickw1** [comment]
I'm just wondering whether this is simply because `three` is included as a dependency in `package.json` for AR.js when `super-three` (a version of three.js) is already a dependency of A-Frame. Thus both `three` and `super-three` are being imported. 

@kalwalt does this make sense?

**Comment by kalwalt** [comment]
Hi to all @FireDragonGameStudio @juanRabaa @Platform-Group in this thread, I merged PR #615 It should solve this issue (for THREEX at least) can you test the dev branch? I will make a new AR.js release in few days. Thanks to all!

**Comment by FireDragonGameStudio** [comment]
Hi and first of all sry for the late reply. Thank you for your time and hard work @kalwalt, but I unfortunately still have the issue with the multiple instances warning. It also appears with minimal setup, when setting up a project in vite for vanillajs, install the npm packages for three.js and ar.js, and import them in main.js.

Maybe I am missing smth here Oo Is it possible to use three.js functionality with ar-threex.js too, like creating scenes and stuff? Or is the npm version or ar.js not up-to-date, with the latest release?

**Comment by kalwalt** [comment]
You should import the ar-threex.mjs package not ar-threex.js. After have installed the package with npm try to import the needed classes in this way `import { ArToolkitProfile } from "@ar-js-org/ar.js/there.js/build/ar-threex.mjs"`

**Comment by FireDragonGameStudio** [comment]
Did exactly that, but unfortunately the warning still appears. Just added a few lines to actually show smth. Sry for being such a nuisance :/

**Code:**
```js
import "./style.css";
import javascriptLogo from "./javascript.svg";
import viteLogo from "/vite.svg";

import { ArToolkitProfile } from "@ar-js-org/ar.js/three.js/build/ar-threex.mjs";
import * as THREE from "three";

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
const renderer = new THREE.WebGLRenderer();
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.setAnimationLoop(animate);
document.body.appendChild(renderer.domElement);

const hemiLight = new THREE.HemisphereLight(0x404040, 0xffffff, 0.5);
scene.add(hemiLight);

const geometry = new THREE.BoxGeometry();
const material = new THREE.MeshStandardMaterial({ color: 0x00ff00 });
const cube = new THREE.Mesh(geometry, material);
cube.position.z = -5;
scene.add(cube);

const rotationSpeed = 0.5;
const clock = new THREE.Clock();

function animate() {
  requestAnimationFrame(animate);

  const delta = clock.getDelta();
  cube.rotation.x += rotationSpeed * delta;
  cube.rotation.y += rotationSpeed * delta;

  renderer.render(scene, camera);
}

window.addEventListener("resize", () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
});
```

**package.json:**
```js
{
  "name": "vite-three-ar",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^6.0.5"
  },
  "dependencies": {
    "@ar-js-org/ar.js": "^3.4.6",
    "three": "^0.172.0"
  }
}
```

**Result:**
![image](https://github.com/user-attachments/assets/f7531279-1ab4-40d4-a224-a017867845d7)

**Comment by kalwalt** [comment]
What happens if you not import the whole THREE namespace but only the single classes (Scene, PerspectiveCamera and so on...) ? Sorry i have no time to test and gor helping in this period...

**Comment by FireDragonGameStudio** [comment]
No worries, it's not blocking., it's still just a warning. Unfortunately using the single classes doesn't help, the warning is still there.

**Comment by kalwalt** [comment]
@FireDragonGameStudio maybe the issue occur because some bundlers require a "module" field in the package.json file. I will try to add it in the Ar.js [package.json](https://github.com/AR-js-org/AR.js/blob/master/package.json) file, but i'm not sure that it will solve the issue, because as main is https://github.com/AR-js-org/AR.js/blob/067057811a815755fe718f83f40674a48a6a8d30/package.json#L5  module will be `"module": "./aframe/build/aframe-ar.mjs"` and not   `"module": "./three.js/build/ar-threex.mjs"`. The solution is to add modularity to the whole AR.js project, as discussed elsewhere, this is on my ticked list but i can't say when it will happens.

**Comment by kalwalt** [comment]
I could add the module version to [Arjs-threejs](GitHub.com/AR-js-org/ARjs-threejs). I will post here when it'ready. 🙂

**Comment by kalwalt** [comment]
For anyone interested: working on this PR https://github.com/AR-js-org/AR.js-threejs/pull/22

**Comment by kalwalt** [comment]
I succesfully merged the PR and i think solved the issue , at least in AR.js-threejs, You can test in the [AR.js-threejs example-vite](https://github.com/AR-js-org/AR.js-threejs/tree/main/example-vite) or i have created a testing repository on my profile [ar.js-threejs-test](https://github.com/kalwalt/ar.js-threejs-test). i noticed that i got the Three.js multiple instnces warning if the three.js version diverge ( the one installed in AR.js-threejs and that one in the vite project) they should be the same 0.164.0 in any package.json files. Maybe you can test @FireDragonGameStudio? Thank you!

**Comment by kalwalt** [comment]
> Did exactly that, but unfortunately the warning still appears. Just added a few lines to actually show smth. Sry for being such a nuisance :/
> 
> **Code:**
> 
> ```js
> import "./style.css";
> import javascriptLogo from "./javascript.svg";
> import viteLogo from "/vite.svg";
> 
> import { ArToolkitProfile } from "@ar-js-org/ar.js/three.js/build/ar-threex.mjs";
> import * as THREE from "three";
> 
> const scene = new THREE.Scene();
> const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
> const renderer = new THREE.WebGLRenderer();
> renderer.setSize(window.innerWidth, window.innerHeight);
> renderer.setAnimationLoop(animate);
> document.body.appendChild(renderer.domElement);
> 
> const hemiLight = new THREE.HemisphereLight(0x404040, 0xffffff, 0.5);
> scene.add(hemiLight);
> 
> const geometry = new THREE.BoxGeometry();
> const material = new THREE.MeshStandardMaterial({ color: 0x00ff00 });
> const cube = new THREE.Mesh(geometry, material);
> cube.position.z = -5;
> scene.add(cube);
> 
> const rotationSpeed = 0.5;
> const clock = new THREE.Clock();
> 
> function animate() {
>   requestAnimationFrame(animate);
> 
>   const delta = clock.getDelta();
>   cube.rotation.x += rotationSpeed * delta;
>   cube.rotation.y += rotationSpeed * delta;
> 
>   renderer.render(scene, camera);
> }
> 
> window.addEventListener("resize", () => {
>   camera.aspect = window.innerWidth / window.innerHeight;
>   camera.updateProjectionMatrix();
>   renderer.setSize(window.innerWidth, window.innerHeight);
> });
> ```
> 
> **package.json:**
> 
> ```js
> {
>   "name": "vite-three-ar",
>   "private": true,
>   "version": "0.0.0",
>   "type": "module",
>   "scripts": {
>     "dev": "vite",
>     "build": "vite build",
>     "preview": "vite preview"
>   },
>   "devDependencies": {
>     "vite": "^6.0.5"
>   },
>   "dependencies": {
>     "@ar-js-org/ar.js": "^3.4.6",
>     "three": "^0.172.0"
>   }
> }
> ```
> 
> **Result:** ![image](https://private-user-images.githubusercontent.com/23502690/400025719-f7531279-1ab4-40d4-a224-a017867845d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3OTM3MTcsIm5iZiI6MTczNjc5MzQxNywicGF0aCI6Ii8yMzUwMjY5MC80MDAwMjU3MTktZjc1MzEyNzktMWFiNC00MGQ0LWEyMjQtYTAxNzg2Nzg0NWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDE4MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZDAyYTE2NmU5MDg1N2JmMTQxMTJjOGMyZTkwMDhhZDFkNzQ2NmUyODIxZjA4ZmI1NTcyZDA5NjY0YWE1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tIkhVFKUmYrRo7aJH9TAW6v3FsCbmqzadg4pTCexSJY)

@FireDragonGameStudio  in regards of my previous comment can you test again this code with `"three": "^0.164.0"` instead?

**Comment by FireDragonGameStudio** [comment]
OMG, changing the three.js version did the trick! The warning disappeared @kalwalt 🙀

**Comment by FireDragonGameStudio** [comment]
You're a genius, I would've never thought of that as the warnings cause!

**Comment by kalwalt** [comment]
> You're a genius, I would've never thought of that as the warnings cause!

I have never thought of that too, I will add a Post Edit on the top of this topic as a reminder for other people 😄
